name: lab8
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.0
  intl: ^0.20.2
  http: ^0.13.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - C:\Users\User\Desktop\mobile_dev\lab8\lib\othrers\pic.json